# Apply shell configuration by including the following line in bashrc/zprofile:
# source ~/.swt/shell/bashrc

# syntax error near unexpected token `elif'
# is caused by Git converting files to CRLF
# https://stackoverflow.com/questions/4182122/syntax-error-near-unexpected-token-elif

# Resolve $DOTSWT root in shell-agnostic and path-agnostic way
# https://stackoverflow.com/questions/9901210/bash-source0-equivalent-in-zsh
ZSH_SOURCE=${BASH_SOURCE[0]:-${(%):-%x}}
if [ -n "$ZSH_SOURCE" ]; then
    export DOTSWT=$(dirname $(dirname $ZSH_SOURCE))
else
    export DOTSWT=$(dirname $(dirname $0))
fi

source $DOTSWT/shell/common
