# Workaround for Windows Terminal.
# Issue reproducible on Windows 11 25H2 in June 2026.
# https://github.com/microsoft/terminal/issues/18004
set-option -sg escape-time 40

# Remove the default prefix
unbind C-b

# Set Ctrl+Space (NUL) as the new prefix
set -g prefix C-Space
bind C-Space send-prefix

