# Based on:
# https://github.com/jesse-a-l-hamer/hyprland-dots/blob/main/hyprqt6engine.conf
#
# Upstream documentation:
# https://wiki.hypr.land/Hypr-Ecosystem/hyprqt6engine/

theme {
    # color_scheme = /usr/share/qt6ct/colors/catppuccin-macchiato-flamingo.conf
    color_scheme = /usr/share/color-schemes/BreezeDark.colors # KDE theme
    # icon_theme   = Papirus-Dark
    # style        = kvantum-dark
    # font_fixed   = "VictorMono Nerd Font"
    # font         = "VictorMono Nerd Font Propo"
}

